version: '3'

services:
  nginx:
    container_name: nginx
    image: xuexb/blog:nginx-latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - blog
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
  blog:
    container_name: blog
    image: xuexb/blog:node-latest
    restart: always
    env_file:
      - ../.env

networks:
  default:
    external:
      name: blog-net