name: deploy v5.xuexb.com

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-v5:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PERSONAL_ACCESS_RW_NAME }}
          password: ${{ secrets.PERSONAL_ACCESS_RW_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Update Nginx Dockerfile path
        run: |
          a=xuexb/blog:node-latest
          b=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:node-${{ steps.meta.outputs.version }}
          sed -i "s?$a?$b?g" docker/Dockerfile.nginx
          cat docker/Dockerfile.nginx
      - name: Build Node.js Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:node-${{ steps.meta.outputs.version }}
      - name: Build Nginx Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.nginx
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nginx-${{ steps.meta.outputs.version }}